### ISSUE TITLE
Do you have a translation API ?

### ISSUE THREAD

**Issue by redflake** [WeAreMahsaAmini/TwitterScraper#5]
The question is, do we need a translation API for persian to English?

**Comment by v8hid** [comment]
@redflake  I thought about translation API, but there is no reliable api for translating Persian to English, if you have any idea let me know

**Comment by redflake** [comment]
As you might know the most accurate should be google translate, but then it must be reviewed. 

https://cloud.google.com/translate

pricing: 
Total usage for language detection and text translation by using the NMT model | First 500,000 characters* per month | Free

Note: google might also support the movement

**Comment by v8hid** [comment]
Thanks for the useful information, We already translated more than 300 tweets from Persian to English but if we decided translate in other language, using an api would be a great idea 💡
