### ISSUE TITLE
Is it possible to commit our idea to git

### ISSUE THREAD

**Issue by nimayazdi93** [WeAreMahsaAmini/TwitterScraper#8]
hi, is it possible to commit our idea to git? which branch we should use?

**Comment by v8hid** [comment]
Sure, I just added the contribution part on readme part.
Just share your ideas here I can create a branch, or create it on your fork and open a pull request.

**Comment by nimayazdi93** [comment]
Very tnx
I had a idea for connecting cards to real tweet by a link, and also we can have a retweet link on retweet icon
I already tested this idea , it’s a small commit that you can make it too.

**Comment by v8hid** [comment]
We will do that in the next phase, but if you are a Vue.Js feel free to contribute.

**Comment by nimayazdi93** [comment]
Dear vahid, i have commited on my fork. and i will share my idea with you same as this issue. very tnx
